### ISSUE TITLE
这几个参数分别对应什么

### ISSUE THREAD

**Issue by erichuang1995** [leng-yue/py-scrcpy-client#1]
https://github.com/leng-yue/py-scrcpy-client/blob/0604f3836e24f2c15da4304cf57e21beeedf438c/scrcpy/core.py#L107

**Comment by leng-yue** [comment]
可以先参考官方实现 我过几个小时把这块的注释加上

**Comment by leng-yue** [comment]
已经加上了注释, 如果有帮助希望能给个 star
