### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by rhobro** [leng-yue/py-scrcpy-client#10]
I connected my phone and opened up scrcpy and an opencv window with the inputs form py-scrcpy-client.

When I had them side by side, I noticed that scrcpy was instant while py-scrcpy-client had a roughly 3 to 5 second lag. Why is this the case?

**Comment by rhobro** [comment]
The same lag occurs with and without the scrcpy window open.

**Comment by leng-yue** [comment]
This is weird. Can you check whether your CPU is overloaded?

**Comment by leng-yue** [comment]
By the way, are you using the `scrcpt-client[ui]`?

**Comment by rhobro** [comment]
> This is weird. Can you check whether your CPU is overloaded?

Despite running both scrcpy and py-scrcpy-client at the same time, the CPU load is minimal.
Now that I have changed network, the lag seems to have reduced but py-scrcpy-client is definitely lagging behind by a second or two.

No, I'm not using scrcpy-client[ui]. Is this the problem?

<img width="197" alt="Screenshot 2021-11-11 at 19 41 09" src="https://user-images.githubusercontent.com/54175175/141358765-269d3fac-a2e4-4f35-92fc-f1179f9dd4a9.png">
ok

**Comment by leng-yue** [comment]
As you mentioned network, are you using wifi to connect to the device?  
Can you test official scrcpy 1.18?

**Comment by leng-yue** [comment]
Maybe there is some problem with wifi port forwarding, can you also test the USB connection?

**Comment by rhobro** [comment]
I was using Wi-fi to connect to the device. Seeing the lag, I switched to usb but the lag was still there.

**Comment by rhobro** [comment]
I'll test 1.18 and report the results.

**Comment by rhobro** [comment]
I am already on 1.19 and don't need to update to 1.18

**Comment by rhobro** [comment]
Can py-scrcpy-client start using v1.19 of scrcpy-server?

**Comment by leng-yue** [comment]
I planed to update to 1.20 when it's published.

**Comment by leng-yue** [comment]
Since scrcpy always publishes new versions, I don't have enough time to follow every small version.

**Comment by rhobro** [comment]
When will that be?

**Comment by leng-yue** [comment]
If scrcpy doesn't publish v1.20 this month, I will upgrade to 1.19.

**Comment by rhobro** [comment]
Ok. Thanks. When you do upgrade, please let me know.

**Comment by rhobro** [comment]
Scrcpy v1.20 has been released.

**Comment by leng-yue** [comment]
Great! I will upgrade the scrcpy-client in about three days.

**Comment by leng-yue** [comment]
A new version is publishing, can you try it later?

**Comment by leng-yue** [comment]
> I was using Wi-fi to connect to the device. Seeing the lag, I switched to USB but the lag was still there.

How much is the lag on USB? I didn't find a lag on my devices :(

**Comment by rhobro** [comment]
I'll try it later.

The lag on usb with the old version was about 1 to 2 seconds

**Comment by leng-yue** [comment]
any update?

**Comment by rhobro** [comment]
There is still a 1 to 2 second lag via USB

**Comment by leng-yue** [comment]
I will try to figure out why this happens when I have time, and the issue won't be closed until the problem is solved.

**Comment by rhobro** [comment]
Ok. Thank you. Here is some context for when you're looking. I'm running macOS Monterey on an Intel Mac.

**Comment by leng-yue** [comment]
I am using macOS Monterey + mac m1 max, so I need to migrate ADB to mac m1 first...

**Comment by leng-yue** [comment]
I can't reproduce the lag.

**Comment by leng-yue** [comment]
![image](https://user-images.githubusercontent.com/25119060/142750731-76be427e-9cfa-43ad-b445-77b32fec8f7d.png)

**Comment by leng-yue** [comment]
can you send me a similar timer screenshot?

**Comment by rhobro** [comment]
For some reason when I use opencv to show the display side by side with scrcpy, the lag is roughly 100ms but when I don't, it is roughly 500ms

**Comment by leng-yue** [comment]
Seems like a Qt rendering problem?

**Comment by leng-yue** [comment]
My screenshot shows that the lag on my laptop is about 30ms

**Comment by leng-yue** [comment]
Can you try the newest py-scrcpy? I updated some parts in the UI rendering.

**Comment by leng-yue** [comment]
I found the problem, it is here
https://github.com/leng-yue/py-scrcpy-client/blob/de17bb4b5f3651cb9580a5dc1cda65e0426f3430/scrcpy/core.py#L181-L194

Using [this code](https://stackoverflow.com/questions/62759863/how-to-use-pyav-or-opencv-to-decode-a-live-stream-of-raw-h-264-data), I can get the same latency as the official scrcpy. However, the stream is not stable and may raise errors. If you have any ideas to solve this problem, please share them with me.

**Comment by rhobro** [comment]
Does OpenCV use Qt to render?

**Comment by rhobro** [comment]
Aha, What was the issue?

I'll try it with that code
