### ISSUE TITLE
Show "loading" when i run main.py

### ISSUE THREAD

**Issue by allen2000** [leng-yue/py-scrcpy-client#13]
Hi，when i use a phone connected to my pc, and check adb devices is show the serial number, then i run main.py (v0.3.7), py-client 
 just show  "loading" and have not response.  And i use original scrcpy(v1.12) run is ok, Would your help me to debug it? TKS.

phone config:
Android 9
resolution: 1200x800

ps: I have another phone just run py-client OK.

**Comment by leng-yue** [comment]
Can you make sure that the adb is connected? You can use the `adb devices` command.

**Comment by allen2000** [comment]
> Can you make sure that the adb is connected? You can use the `adb devices` command.
Yes, i am sure. I connect two devices. and one is OK, another one show "loading", first i just think maybe the phone setting, but i check the phone develop setting the same as the OK one.

**Comment by leng-yue** [comment]
So you can see both devices in the options, but you can't connect to it. Is that correct?
