### ISSUE TITLE
华为鸿蒙系统接入手机，卡死不能用

### ISSUE THREAD

**Issue by lycfr** [leng-yue/py-scrcpy-client#16]
RT

**Comment by lycfr** [comment]
有办法调试一下吗？我直接用scrcpy源生的是可以的

**Comment by lycfr** [comment]
我debug了一下，卡在这边
![image](https://user-images.githubusercontent.com/29672247/150316628-1c281226-756c-4694-bb7e-cc1e6c112cfb.png)
可能是手机端server没启动起来还是被终止了

**Comment by leng-yue** [comment]
如果是 server 没起来, tcp 会直接连不上, 应该不会是空数据包. 手上没有鸿蒙设备, 可能得你自己调试了.

**Comment by lycfr** [comment]
鸿蒙系统手机
![image](https://user-images.githubusercontent.com/29672247/150713550-8ecf04f9-6a49-4aaf-8106-477f01090563.png)
其他手机
![image](https://user-images.githubusercontent.com/29672247/150713587-d3550306-275c-4ed6-b821-bea435df2c1a.png)
这2个server起来好像不一样，鸿蒙起server就终止了，其他手机好像不会

**Comment by leng-yue** [comment]
这块我不太清楚, 可能是鸿蒙修改了权限控制相关代码?

**Comment by lycfr** [comment]
你这个是直接用了scrcpy-server编译的jar吗？我直接用scrcpy是可以投屏的。方便加个Q沟通一下，Q：1354592998

**Comment by leng-yue** [comment]
这个 jar 直接用的 scrcpy 原版的 server, 你可以手动启动 server 测试.

**Comment by x931890193** [comment]
试试把比特率调低呢

**Comment by AmazingRaise** [comment]
不只是鸿蒙，我试了好多个终端，都会出现空包的情况（基于scrcpy 1.23版本）。想mark下，有空去尝试

**Comment by leng-yue** [comment]
嗯嗯, 你有空测测? 我不是很清楚为什么会空包
