### ISSUE TITLE
pip安装不了都是显示红色

### ISSUE THREAD

**Issue by fujvy1** [leng-yue/py-scrcpy-client#18]
![屏幕截图 2022-03-06 181724](https://user-images.githubusercontent.com/87294559/156918887-66834955-8d75-4352-9336-bcaa236a9d37.png)

**Comment by leng-yue** [comment]
这是你pip出问题了吧... 自己换源看看

**Comment by leng-yue** [comment]
https://stackoverflow.com/questions/67297278/valueerror-check-hostname-requires-server-hostname
