### ISSUE TITLE
API documentation doesn't have examples 

### ISSUE THREAD

**Issue by nimagp** [leng-yue/py-scrcpy-client#19]
Please, just for respecting humanity, create a proper doc for your code
How in the mars can I find out that what is this int parameter in back_or_turn_screen_on function?
![Screenshot_2022-04-29_01-22-58](https://user-images.githubusercontent.com/71447191/165843778-cbf360d2-3fec-4def-9a50-0242fc3d385c.png)
And you didn't mention anywhere what is that ACTION_DOWN
And its just *one* function 
Thanks very much

**Comment by leng-yue** [comment]
Hi, `ACTION_DOWN` is defined in `scrcpy/const.py`. 

Your IDE should suggest you add `from scrcpy import ACTION_DOWN`, when you type `ACTION_DOWN`.

**Comment by nimagp** [comment]
Sorry I didn't notice.
anyways,thanks
