### ISSUE TITLE
如何通过tcp连接到设备

### ISSUE THREAD

**Issue by killaragorn** [leng-yue/py-scrcpy-client#2]
您好，我目前想做的是移植一个C#版本的ScrcpyClient。
我首先阅读了Sctcpy仓库的Developer.md，了解了工作机理。
之后查到了您的仓库。阅读了代码之后我产生了一些疑问。希望能够得到您的解答！
- [scrcpy/core.py#L76](https://github.com/leng-yue/py-scrcpy-client/blob/0604f3836e24f2c15da4304cf57e21beeedf438c/scrcpy/core.py#L76 ) 这里为什么连接127.0.0.1的5037端口得到的是video_socket  而在下一次调用之后得到的是control_socket？
- https://github.com/leng-yue/py-scrcpy-client/blob/0604f3836e24f2c15da4304cf57e21beeedf438c/scrcpy/core.py#L48 这里是不是应该是self.control_socket.close()

期待得到您的回复！

**Comment by killaragorn** [comment]
补充：通过阅读Adb 协议之后，发现可以使用 localabstract：address 这种方式来得到andrioid对应的socket，我本人对安卓开发并不了解，难道说对scrcpy这个命名的socket，第一次连接就是video_socket，第二次连接就是control_socket，这是socket_sercer.jar中所设置的么？

**Comment by leng-yue** [comment]
1. 对的, 这就是 scrcpy-server 的设计, 第一次连接是 video, 第二次是 control.  
2. control_socket close 这里是我写错了, 已修复. 
3. 我的代码实现用的就是 local abstract, 这样的好处是可以省去端口转发 + 分配端口的过程.

**Comment by killaragorn** [comment]
感谢解惑！
