### ISSUE TITLE
Screen showing green artifact with log

### ISSUE THREAD

**Issue by semarainc** [leng-yue/py-scrcpy-client#22]
hi,
i have problem when trying to run command py-scrcpy, and it shows only green image, but the control is functional.
this happen in network and usb connection

Phone Info (if needed): Samsung S20
here is the screenshot
![image](https://user-images.githubusercontent.com/19622207/168347182-161af352-4e7e-4588-9b91-43af0f79358f.png)

Here is some of the log

> negative number of zero coeffs at 0 0
error while decoding MB 0 0
mb_type 35 in P slice too large at 5 0
error while decoding MB 5 0
P sub_mb_type 5 out of range at 56 0
error while decoding MB 56 0
top block unavailable for requested intra mode
error while decoding MB 13 0
mb_type 46 in P slice too large at 4 0
error while decoding MB 4 0
P sub_mb_type 14 out of range at 34 0
error while decoding MB 34 0
cbp too large (102) at 2 0
error while decoding MB 2 0
cbp too large (120) at 2 0
error while decoding MB 2 0
out of range intra chroma pred mode

Full Log: [mylog.log](https://github.com/leng-yue/py-scrcpy-client/files/8690129/mylog.log)

thanks

**Comment by leng-yue** [comment]
Seems like there is a decoding error, what's your Android version?

**Comment by leng-yue** [comment]
Hi, I added a decoder option. Can you try that?

**Comment by semarainc** [comment]
Sorry for late reply,
Im on android 11

I'll try after finish working

**Comment by semarainc** [comment]
hi, 
i've tested it

![image](https://user-images.githubusercontent.com/19622207/169005000-d0f74ec4-f09d-4860-ac23-31b3041b6298.png)

just stuck on loading and no logs are shown, 
i already tested on all encoder option
i already make sure that usb and wifi connection is working by testing with scrcpy command

when i press ctrl + c i only got this

> Traceback (most recent call last):
  File "/home/telmi/.cache/pypoetry/virtualenvs/scrcpy-client-1z_dp_ia-py3.10/bin/py-scrcpy", line 5, in <module>
    main()
  File "/home/telmi/github/py-scrcpy-client/scrcpy_ui/main.py", line 192, in main
    m.client.start()
  File "/home/telmi/github/py-scrcpy-client/scrcpy/core.py", line 188, in start
    self.__stream_loop()
  File "/home/telmi/github/py-scrcpy-client/scrcpy/core.py", line 209, in __stream_loop
    raw_h264 = self.__video_socket.recv(0x10000)
KeyboardInterrupt

i hope this can help

**Comment by leng-yue** [comment]
Can you try the newest version, the problem should be solved.

**Comment by leng-yue** [comment]
Sounds good :)
