### ISSUE TITLE
ENCODE

### ISSUE THREAD

**Issue by ksuzero** [leng-yue/py-scrcpy-client#24]
EI type 189 size 1776 truncated at 26
SEI type 0 size 144 truncated at 1
sps_id 32 out of range
sps_id 32 out of range
 (repeated 12 more times)
sps_id 14 out of range
sps_id 32 out of range
sps_id 32 out of range
sps_id 14 out of range
sps_id 32 out of range
FMO
is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
FMO
is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
 (repeated 6 more times)
no frame!
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
missing picture in access unit with size 11
Invalid NAL unit 0, skipping.
no frame!
missing picture in access unit with size 11
Invalid NAL unit 0, skipping.
no frame!
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
 (repeated 9 more times)
no frame!
non-existing PPS 3 referenced
Invalid NAL unit 0, skipping.
no frame!
SEI type 8 size 88 truncated at 40
Invalid NAL unit 0, skipping.
SEI type 71 size 1256 truncated at 40
SEI type 134 size 1696 truncated at 40
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
SEI type 197 size 1208 truncated at 40
sps_id 32 out of range
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
sps_id 32 out of range
sps_id 32 out of range
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
sps_id 32 out of range
reference overflow (pps)
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
sps_id 1 out of range
sps_id 8 out of range
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
 (repeated 97 more times)
illegal reordering_of_pic_nums_idc 32
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
 (repeated 3 more times)
no frame!
missing picture in access unit with size 11
missing picture in access unit with size 11
 (repeated 2 more times)
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
no frame!
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
 (repeated 7 more times)
non-existing PPS 215 referenced
Invalid NAL unit 0, skipping.
no frame!
SEI type 3 size 1384 truncated at 40
SEI type 68 size 288 truncated at 40
Invalid NAL unit 0, skipping.
Invalid NAL unit 0, skipping.
SEI type 133 size 1696 truncated at 40
SEI type 197 size 1872 truncated at 40

**Comment by ksuzero** [comment]
[Android12

**Comment by ksuzero** [comment]
API可以正常运行  但是滑屏一会  就会一直报这个输出   画面就卡住不动了

**Comment by leng-yue** [comment]
您先试试 scrcpy-client 3.7 版本, 4.* 好像和 pyav 的兼容有点问题

**Comment by leng-yue** [comment]
Sorry for late replay, this problem is solved in the newest version
