### ISSUE TITLE
Screen showing green artifact with log

### ISSUE THREAD

**Issue by qq1731136590** [leng-yue/py-scrcpy-client#26]
first can work，a little while，It can be controlled but the picture turns green

DEVICE:MI8
(Thank you！I love this project😏😏😏)
LOG:
top block unavailable for requested intra mode -1
error while decoding MB 24 0, bytestream 18661
top block unavailable for requested intra mode -1
error while decoding MB 55 0, bytestream 11295
top block unavailable for requested intra mode -1
error while decoding MB 65 0, bytestream 17219
top block unavailable for requested intra mode
error while decoding MB 27 0, bytestream 11799
top block unavailable for requested intra mode
error while decoding MB 36 0, bytestream 18461
top block unavailable for requested intra mode -1
error while decoding MB 55 0, bytestream 11343
top block unavailable for requested intra mode -1
error while decoding MB 31 0, bytestream 18375
top block unavailable for requested intra mode -1
error while decoding MB 13 0, bytestream 12189
top block unavailable for requested intra mode -1
error while decoding MB 25 0, bytestream 18605
top block unavailable for requested intra mode
error while decoding MB 53 0, bytestream 11157
top block unavailable for requested intra mode
error while decoding MB 53 0, bytestream 11125
error while decoding MB 31 8, bytestream -19
top block unavailable for requested intra mode
error while decoding MB 53 0, bytestream 11157

**Comment by leng-yue** [comment]
Sorry for late replay, this problem is solved in the newest version
