### ISSUE TITLE
无法获取视频流

### ISSUE THREAD

**Issue by xiaohei114** [leng-yue/py-scrcpy-client#27]
我在我的荣耀9x上，尝试使用"pip install scrcpy-client[ui]、py-scrcpy"，他成功运行了，但是没有画面。非常抱歉的是，我只有这一部手机，所以我没法在另外的机器上进行测试(或许可以试一下模拟器)。

我的设备信息：
名称：HONOR9X (荣耀9x)
系统：Harmony2.0.0 (鸿蒙)
型号：HLK-AL00
内存：6.0GB

后来我尝试git拉取源码并调试，确实在调试中发现了一点问题。下面是图片。

首先是使用debug进行调试，发现获取不到视频流，读取到的字节为空。
![Snipaste_2022-05-31_22-25-54](https://user-images.githubusercontent.com/84182130/171197677-963c3b47-c65a-48d0-83ab-3cc5f644dece.png)

这是在使用 py-scrcpy-client 时 scrcpy-server 的显示信息
![Snipaste_2022-05-31_22-27-25](https://user-images.githubusercontent.com/84182130/171197986-b9a33eb5-073c-4ba2-b610-42f9d4868d7f.png)

这是在使用 scrcpy-client 时 scrcpy-server 的显示信息
![Snipaste_2022-05-31_22-29-42](https://user-images.githubusercontent.com/84182130/171198509-3da6b171-3b67-43e1-80ef-68947d8aede4.png)

由于我对Android不是很熟悉，暂时不明白时什么原因导致的，根据我搜索的资料来看，可能是因为鸿蒙系统对于Android的定制化程度比较深的原因。
我会尽量想办法解决这个问题 :(

**Comment by xiaohei114** [comment]
我尝试使用了 1.24 版本的 server-cilent，根据 scrcpy 的提示，我成功修改源码并 debug 了。
我拿到了错误日志，我觉得我应该快解决这个问题了。
![Uploading Snipaste_2022-05-31_22-25-54.png…]()

**Comment by xiaohei114** [comment]
还有各种小问题，不过最主要的问题解决了，有画面也可以操作了，感谢作者❤️
![Snipaste_2022-06-01_04-00-27](https://user-images.githubusercontent.com/84182130/171274645-bcdcd3b4-a7fe-48b6-8269-aa4ba4e4e204.png)

**Comment by leng-yue** [comment]
厉害👍, 不过目前 1.24 有点问题, 已经回滚了. 你可以看下在最新版本上那些小问题还在不在.

**Comment by Cerber2ol8** [comment]
> 我尝试使用了 1.24 版本的 server-cilent，根据 scrcpy 的提示，我成功修改源码并 debug 了。 我拿到了错误日志，我觉得我应该快解决这个问题了。 ![Snipaste_2022-06-01_02-52-08](https://user-images.githubusercontent.com/84182130/171263845-67499645-c777-46bd-b18e-12947c8c8437.png)

可否请问下您是如何解决该问题的

**Comment by xiaohei114** [comment]
非常抱歉，这是我很早之前的研究了，现在大部分内容已经没有印象了，而且当时比较激动，就忘记了说是如何解决的。

如果你愿意的话，可以给我的邮箱3440556848@qq.com发送您的联系方式，我可以通过远程的方式帮你看看。

**Comment by xiaohei114** [comment]
> > 我尝试使用了 1.24 版本的 server-cilent，根据 scrcpy 的提示，我成功修改源码并 debug 了。 我拿到了错误日志，我觉得我应该快解决这个问题了。 ![Snipaste_2022-06-01_02-52-08](https://user-images.githubusercontent.com/84182130/171263845-67499645-c777-46bd-b18e-12947c8c8437.png)
> 
> 可否请问下您是如何解决该问题的

非常抱歉，这是我很早之前的研究了，现在大部分内容已经没有印象了，而且当时比较激动，就忘记了说是如何解决的。

如果你愿意的话，可以给我的邮箱[3440556848@qq.com](mailto:3440556848@qq.com)发送您的联系方式，我可以通过远程的方式帮你看看。

**Comment by Cerber2ol8** [comment]
> > > 我尝试使用了 1.24 版本的 server-cilent，根据 scrcpy 的提示，我成功修改源码并 debug 了。 我拿到了错误日志，我觉得我应该快解决这个问题了。 ![Snipaste_2022-06-01_02-52-08](https://user-images.githubusercontent.com/84182130/171263845-67499645-c777-46bd-b18e-12947c8c8437.png)
> > 
> > 
> > 可否请问下您是如何解决该问题的
> 
> 非常抱歉，这是我很早之前的研究了，现在大部分内容已经没有印象了，而且当时比较激动，就忘记了说是如何解决的。
> 
> 如果你愿意的话，可以给我的邮箱[3440556848@qq.com](mailto:3440556848@qq.com)发送您的联系方式，我可以通过远程的方式帮你看看。

感谢回复，已经找到问题了，ui中设定`bitrate=1000000000` 与默认值8000000不同，将其注释掉即可
