### ISSUE TITLE
请问下如何控制

### ISSUE THREAD

**Issue by a512154224** [leng-yue/py-scrcpy-client#30]
目前启动后只能查看不能控制，还有一个参数名错了client.max_width这是最大尺寸高度

**Comment by leng-yue** [comment]
https://github.com/leng-yue/py-scrcpy-client/blob/3976ef2e547b2864851968abc1735e02e1006e55/scrcpy/core.py#L150

如上所述, `max_width` 中的 `width` 指的是长边. 

关于启动后只能查看不能控制的问题, 你能提供下错误信息吗 :)

**Comment by a512154224** [comment]
你好，没有错误日志输出，鼠标在镜像区域的样式是十字（类似截图的+号），就是无法操作

**Comment by leng-yue** [comment]
你用的什么设备呢

**Comment by wploey** [comment]
> 你好，没有错误日志输出，鼠标在镜像区域的样式是十字（类似截图的+号），就是无法操作

鼠标操作需要自己绑定事件吧，点击时获取到的坐标用 control 里面的方法发送进去🤣
