### ISSUE TITLE
你好，请问usb接收回来的视频是否可以压缩一下

### ISSUE THREAD

**Issue by liuqiao1995** [leng-yue/py-scrcpy-client#39]
作者你好，请问usb接收回来的视频是否可以压缩一下，占用的内存比较大，请问有啥方法可以给获取到的图片压缩一下？

**Comment by leng-yue** [comment]
https://leng-yue.github.io/py-scrcpy-client/guide.html#reduce-cpu-usage

 可以调整下 fps, 图片宽度, 和码率.
