### ISSUE TITLE
adb 错误

### ISSUE THREAD

**Issue by cgcgcg-xs** [leng-yue/py-scrcpy-client#4]
程序打包前正常，打包后提示 adb 错误 （找不到adb.exe，问题是adb.exe已加入PATH了）
[Errno subprocess] .\adb.EXE -s QECDU16E01001589 push C:\Users\ADMINI~1\AppData\Local\Temp\_MEI184962\scrcpy/scrcpy-server.jar /data/local/tmp/: "adb: error: cannot stat 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI184962\\scrcpy/scrcpy-server.jar': No such file or directory\r\n"

找到问题了，不是找不到adb.exe，是找不到scrcpy/scrcpy-server.jar，修改了下路径，搞定了！

**Comment by leng-yue** [comment]
你用的 pyinstaller? 那个好像要用 MEIPASS 之类的参数
