### ISSUE TITLE
ConnectionError: Video stream is disconnected

### ISSUE THREAD

**Issue by jinxiangwzh** [leng-yue/py-scrcpy-client#41]
I use scrcpy can connect success, but I run `py-scrcpy` raise the error below. And I want to take part in this project, is there have any document?
![image](https://user-images.githubusercontent.com/17423179/207238616-5536d366-cb13-46f7-b621-e81e1b764124.png)

**Comment by leng-yue** [comment]
This means that the client's video stream to the scrcpy-server is disconnected. To help me analyze the problem:

- Can you provide the information on your Android device (like the System Version and Manufacturer)?
- Does the [official scrcpy v1.20](https://github.com/Genymobile/scrcpy/releases/tag/v1.20) works on your case? If it doesn't, does the newest version works?
- Can you change the log level to verbose https://github.com/leng-yue/py-scrcpy-client/blob/46934ef5288fe3c1f886d0c6bef03794e7a3f6a0/scrcpy/core.py#L154 and read some outputs from it? (So that we can see if there is any error message).

**Comment by leng-yue** [comment]
Feel free to open this issue again if there is any update.

**Comment by marisancans** [comment]
Im having the same issue, resular scrcpy works for me,
im using:
scrcpy 1.12.1

dependencies:
 - SDL 2.0.10
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100

Changing core.py log level to "verbose" doesnt yield and information on how to fix this except a stack trace.


Also scrcpy_ui/main.py doesnt work out of the box (git pull)
python3 scrcpy_ui/main.py  and cd  && python3 main.py throws  error: ImportError: attempted relative import with no known parent package

**Comment by marisancans** [comment]
Interestingly this simple code does work for me:

```
import scrcpy
# If you already know the device serial
client = scrcpy.Client(device="DEVICE SERIAL")
# You can also pass an ADBClient instance to it
from adbutils import adb
adb.connect("127.0.0.1:5555")
client = scrcpy.Client(device=adb.device_list()[0])


import cv2

def on_frame(frame):
    # If you set non-blocking (default) in constructor, the frame event receiver 
    # may receive None to avoid blocking event.
    if frame is not None:
        # frame is an bgr numpy ndarray (cv2' default format)
        cv2.imshow("viz", frame)
    cv2.waitKey(10)

client.add_listener(scrcpy.EVENT_FRAME, on_frame)

client.start()
```

**Comment by leng-yue** [comment]
So while the simple one works, the above doesn't work for you? The only difference is that the cli uses threading. Can you try add `threaded=True` to the `client.start` for the simple one?

**Comment by onesu-obolik** [comment]
Hello, I have exactly the same issue. The demo code posted by  marisancans doesn't show anything, terminal just stay empty. If I add ("print") markers to know where the error comes from, it seems it blocks when opencv2 is supposed to render the frame. 
With py-scrcpy, the name of the phone appears for a millisecond before closing windows and giving the same "video stream is disconnected".
with the even simpler demo here below, phone screen reacts and gets full light, but that's it. has somebody any better idea? I am losing courage after 2 evenings in a row changing parameters in program for no result...thanks in advance
Phone: Redmi note 7 with E/OS

import cv2 as cv
from pyscrcpy import Client # import scrcpy client


def on_frame(client, frame):
    client.control.text("123")
    cv.imshow('Video', frame)
    cv.waitKey(1)


if __name__ == '__main__':
    client = Client(max_fps=1, max_size=900)
    client.on_frame(on_frame)
    client.start()

**Comment by China-yuzhou** [comment]
我也出现了同样的问题，我仔细阅读了你们的标题和评论，发现、、、、、、、、、、、、、、并没什么解决的方法。有没有大佬出来彻底处理下
