### ISSUE TITLE
华为mate30 鸿蒙4.0系统执行py-scrcpy后报错：ConnectionError: Video stream is disconnected

### ISSUE THREAD

**Issue by fankuneee** [leng-yue/py-scrcpy-client#67]
华为mate30 鸿蒙4.0系统执行py-scrcpy后报错：ConnectionError: Video stream is disconnected
![image](https://github.com/user-attachments/assets/9122f1b7-f23f-4051-a509-b17f13edf7f5)

请问一下如何才能成功投屏

**Comment by zhanghaichao520** [comment]
指定encodername

**Comment by shau88** [comment]
> 指定编码器名称

非常感谢，通过你的回答我使用命令行py-scrcpy --encoder_name c2.android.avc.encoder 完成了输出画面

**Comment by fdgfgdfgdfgdfgdfgdf** [comment]
请问 这个问题在代码连接时怎么编写代码置顶编码器名称呢

**Comment by fdgfgdfgdfgdfgdfgdf** [comment]
> > 指定编码器名称
> 
> 非常感谢，通过你的回答我使用命令行py-scrcpy --encoder_name c2.android.avc.encoder 完成了输出画面

非常感谢，我修改了 venv/Lib/site-packages/scrcpy/core.py              第82行为 self.encoder_name ="c2.android.avc.encoder"

**Comment by Donnyxhc** [comment]
hello，mate60现在也遇到这个情况了，每个encoder都试过了不太行，有什么解决方案吗各位

**Comment by xiaokang00010** [comment]
> hello，mate60现在也遇到这个情况了，每个encoder都试过了不太行，有什么解决方案吗各位

新的代码（支持了scrcpy 2.4后）貌似根本没有指定encoder和codec给服务端，我提了个PR #73 改了一下，不知道什么时候合并
