### ISSUE TITLE
scrcpy shortcut commands not working

### ISSUE THREAD

**Issue by JustinDBruce** [leng-yue/py-scrcpy-client#8]
I am trying to use some of the scrcpy shortcut commands, https://gist.github.com/csarron/b3ab1fc6e5e9da622d675c59137ef2a8

its only simulating keycode events for the device. Is there a way to have them work?

**Comment by leng-yue** [comment]
Please check the [document](https://leng-yue.github.io/py-scrcpy-client/guide.html#send-actions), and https://github.com/leng-yue/py-scrcpy-client/blob/a8222520c09f968ad0449eba280a96e8bd95e29c/scrcpy_ui/main.py#L92-L130
